### ISSUE TITLE
meta tag description is no longer updated

### ISSUE THREAD

**Issue by victorfernandesraton** [nullstack/nullstack#309]
when using prepare for update `context.page.description` not be update meta tags

Nullstack version `0.17.3`

**Comment by Mortaro** [comment]
Heyo, thanks for the report!

Since version 16 Nullstack defaults to SPA mode in the development environment, which skips generating SEO metatags, when you build it will work normally.

You can also disable the optimization in dev mode by changing your package.json to:

```
"scripts": {
    "start": "npx nullstack start --mode=ssr",
    "build": "npx nullstack build"
  }
  ```
  
  Please reopen if this does not solve your issue
