### ISSUE TITLE
The `onerror` event in `img` elements isn't being triggered correctly when SSR is involved

### ISSUE THREAD

**Issue by emanuelmch** [nullstack/nullstack#338]
Example code:
```JSX
<img src={possiblyInvalidUrl} onerror={{ showDefault: true }} />
```
When this is rendered server-side and the browser fails to load the image in `possiblyInvalidUrl`, the `onError` event isn't being triggered. If this is rendered client-side (e.g. if we navigate into the page instead of opening it directly), then the browser triggers the event correctly.

Just to clarify, I don't expect `onerror` to be triggered server-side (because it's a browser thing), but I did expect it to be triggered at some point client-side.

Our use case for this is showing a user's avatar. If the image fails to load for any reason, we want to display a different component.

**Comment by SD007CSE** [comment]
I am new in contribution can you tell me where to find this above line, so that I can give it a try to solve the issue.

**Comment by Mortaro** [comment]
Heyo, sorry for the late response (*/ω＼*),

This issue is probably happening during the hydration process, but it is a bit more complicated than it looks like. 

Right now the way Nullstack loads quickly is by being plain HTML untill all the paints are done, and this error raises during paintint, the best i can think of to solve this without tradeoffs would be to update the client/render.js and maybe client/rerender.js to try load the image again and if an error happen trigger the onerror event again

**Comment by GuiDevloper** [comment]
Were taking a look on this, hard to reproduce since it happens in SSR deploy and first load (when server starts and delivers the first render).

Anyway, a fast fix lies in [`context.environment.client`](https://nullstack.app/context-environment):
```tsx
class Application extends Nullstack {

  showDefault = false
  possiblyInvalidUrl = '/invalid.png'

  render({ environment }: NullstackClientContext) {
    return (
      <>
        {this.showDefault && <h1>Default!!</h1>}
        {environment.client && (
          <img src={this.possiblyInvalidUrl} onerror={{ showDefault: true }} />
        )}
      </>
    )
  }
}
```
